### ISSUE TITLE
Common code

### ISSUE THREAD

**Issue by nobe4** [albertxing/stool#1]
Hello, 

Your project looks great, as I was searching for a easy-to-use alternative to jsperf.

Do you thinks about providing a "common code" functionality ? 

Thanks,

**Comment by albertxing** [comment]
You mean jQuery, etc?
This should be quite simple to add, I'll see if I can get it done within the next couple of days.

**Comment by nobe4** [comment]
I thought more about a code that will be reused across different tests. 

For example : 

common:

```
var a = 0;
```

test 1 : 

```
 a += 1;
```

test 2 : 

```
 a ++;
```

**Comment by albertxing** [comment]
I see, setup code for each test.
This is also a missing feature that needs to be implemented. The main issue with this is UI related, e.g. where do the text boxes go?

**Comment by nobe4** [comment]
What do you mean ?

**Comment by albertxing** [comment]
Setup code is code that runs before each test but isn't timed - for example, `var a = 0`. This would be relatively easy to add JS-wise, but more difficult is the question of how to expose this to the user.

Does that clarify?

**Comment by nobe4** [comment]
Yes, I don't really know though ...

**Comment by albertxing** [comment]
I'll have to think about it a bit more. Hopefully I'll find a good place to put it and get this done soon, it is quite an essential feature.

**Comment by skulptur** [comment]
Just do it like nobe4 exemplified. Common on top, test cases below it. This is the only feature keeping me from using this as the setup code alone is being clocked, I'd have to copy everything to the two boxes to make sure it takes the same amount of time to setup both.

**Comment by albertxing** [comment]
@spredemann I agree with the importance of setup/takedown code for the test cases. I haven't had a lot of time lately to work on the project, hopefully I can merge nobe4's code soon - there are a couple of things I'd like to clean up before I merge.

Please keep reminding me if I don't get this done within the next month :stuck_out_tongue:

**Comment by albertxing** [comment]
#4 merged
