### ISSUE TITLE
Share benchmarks

### ISSUE THREAD

**Issue by sonnyp** [albertxing/stool#2]
Would be awesome to use a url hash with tests code to share benchmarks.
Also stool could rely on 3rd party services such as gists for saving/sharing.

**Comment by albertxing** [comment]
Yes, I've been thinking about doing this. I don't think URL hashes will be feasible, the code may be too long to share.

Gists might be reasonable, I haven't figured out exactly how I'd implement this yet.

**Comment by nobe4** [comment]
You can look at the documentation : 
https://developer.github.com/v3/gists/#create-a-gist

It should do what you want :+1:

**Comment by sonnyp** [comment]
http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

I think 2000chars is good enough for many micro benchmarks.

**Comment by nobe4** [comment]
There you go : 
http://codepen.io/nobe4/pen/BNGpKZ?editors=101

**Comment by albertxing** [comment]
@sonnyp Agreed, however there's the issue of "shareability", e.g. is it okay to share a link that's ~200 characters long?

@nobe4 Thanks for the code snippet. The API is very simple and allows for anonymous posts, which is great. Also, the raw gist allows cross-origin requests, which allows us to retrieve the content via AJAX. The issue of how to integrate this into stool is still an issue. There needs to be a specific input format, and an import from gist option.

**Comment by nobe4** [comment]
Do you want another snippet implementing the other side ?

**Comment by albertxing** [comment]
I don't think it's a matter of implementation - it's more of just deciding how we're going to implement it.
For example, what should the gist syntax be? Should we store each test case in a separate file in a single gist (a gist can have multiple files), or store them all in one file with some kind of separator between them?

**Comment by nobe4** [comment]
I thinks, as we can separate files in gist, we should use it. 
So for example, a file should be named _common and all the others depending on the test name.

**Comment by albertxing** [comment]
:+1: that's what I was thinking as well

**Comment by nobe4** [comment]
Btw I tried to develop some kind of wrapper around benchmark.js, do you think it can be usefull ?

**Comment by albertxing** [comment]
I think the Benchmark API is simple enough, and the code is not a huge mess (yet).
If you'd like to create a new issue regarding this, feel free to do so and we can discuss further

**Comment by nobe4** [comment]
You got it :)

**Comment by albertxing** [comment]
Okay, implemented in 917a90447a
Let me know if there's anything that needs to be changed, I will close this issue otherwise.

Thanks all for the great suggestions!
