### ISSUE TITLE
Code organisation

### ISSUE THREAD

**Issue by nobe4** [albertxing/stool#3]
As said in #2, I tried to mess around using the benchmark.js api to create a sort-of wrapper around It.

I think, if this projet is going to evolve, that the separation between the different parts must be done early.

I was thinking about thoses parts : 
1. Benchmark.js direct wrapper : set options and provide easier way to create/run tests.
2. Dom Manipulation : piping the results from and to benchmark.js

**Comment by albertxing** [comment]
I think the main discussion here should be concerned with whether or not we need a wrapper - in other words, will the code become complex enough to justify the use of such a wrapper?
