### ISSUE TITLE
Bug: Share, modify, share again

### ISSUE THREAD

**Issue by Zorgatone** [albertxing/stool#6]
If you share the test code, then modify and fix something, and then share it again, the URL won't update and you will share the original one again

**Comment by albertxing** [comment]
Thanks for reporting!
I'm having trouble reproducing the bug though - on my computer, the share link disappears when I change something, and when I click Share again a new link appears.

What browser/OS are you? Do you see any errors in the developer console?

**Comment by Zorgatone** [comment]
I was on chrome on OS X.
I will try to reproduce it again tomorrow morning and see if I get I it
again. I don't remember if there were any error in the JavaScript console,
probably

**Comment by Zorgatone** [comment]
It's working now. Here's what I think that happened: I probably had shared some code with a syntax error, then fixed the code and attempted to share again but it didn't update the share URL

**Comment by albertxing** [comment]
I'm still worried about this though, it shouldn't matter what is in the
code - anything, even gibberish, should be shareable.

Let me know if this happens again, and I appreciate your effort :)
