### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by jitcoder** [albertxing/stool#7]
Console error:
https://alight.albertxing.com:8443/ Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
stool.js:34 Suite[2]

Why is this trying to make a connection to a remote server. I thought it was stand alone

**Comment by albertxing** [comment]
Oh 😕 
That's my user stats server (logs visit counts)
Looks like it's down, I'll remove logging until it is fixed.

The app shouldn't break because a network request is failing, I'll need to fix this in the future.

Thanks!

**Comment by albertxing** [comment]
Just wanted to add, the application was not broken for me even though the network request was causing an error. Maybe this is browser-dependent?

Anyway, fixed in 28a889d
